services:
  app:
    build: .
    container_name: stromabrechnung
    ports:
      - "3000:3000"
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
    restart: always
