services:
  app:
    # Use the pre-built image from GitHub Container Registry
    image: ghcr.io/fourtyfiver/stromabrechnung:latest
    container_name: stromabrechnung
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
    restart: always
